### ISSUE TITLE
No timeout set on requests calls

### ISSUE THREAD

**Issue by benjamb** [smarkets/marge-bot#188]
Our instance of marge-bot has been seemingly refusing to pick up new jobs recently, after enabling debug logs, it appears the bot is hanging indefinitely in requests methods, with the last thing to be logged being:

    DEBUG Starting new HTTPS connection (1): gitlab.com

There is a warning with regards to this within the documentation of requests: https://2.python-requests.org/en/master/user/quickstart/#timeouts

Given such timeouts are likely to be caused by transient issues, simply retrying upon hitting a timeout may be the easiest way around this. I've patched our instance with the following:
```
diff --git a/marge/gitlab.py b/marge/gitlab.py
index e5c464a..ebb0f8b 100644
--- a/marge/gitlab.py
+++ b/marge/gitlab.py
@@ -17,7 +17,10 @@ class Api:
         if sudo:
             headers['SUDO'] = '%d' % sudo
         log.debug('REQUEST: %s %s %r %r', method.__name__.upper(), url, headers, command.call_args)
-        response = method(url, headers=headers, **command.call_args)
+        try:
+            response = method(url, headers=headers, **command.call_args, timeout=10)
+        except requests.exceptions.Timeout as err:
+            log.debug('REQUEST TIMEOUT: %s', err)
+            return self.call(command, sudo=sudo)
         log.debug('RESPONSE CODE: %s', response.status_code)
         log.debug('RESPONSE BODY: %r', response.content)
```
However I assume a loop with a max retry count would be preferable for submitting as a PR? The loop could also include retries for #144. I'll await feedback on this issue before submitting anything.

**Comment by aschmolck** [comment]
We should definitely always have a timeout. I'm not 100% sure what the best way to handle the retry logic is. Fundamentally, since the REST API doesn't allow us to do certain things transitionally that one would want to do transitionally, there are some windows for race conditions and retries obviously exacerbate that. I'm leaning towards not doing any retries and just fail and leave a message that the request timed out. Typically it should be easy to recover by just re-assigning marge again, after all if the gitlab setup is not particularly flaky this should happen quite rarely. 

@JaimeLennox what  do you think?

**Comment by thinkl33t** [comment]
We keep seeing an issue that could plausibly be this on our marge bot instance connected to gitlab.com:

```
2019-06-01 02:12:09,071 DEBUG REQUEST: GET https://gitlab.com/api/v4/projects/8014163/merge_requests {'PRIVATE-TOKEN': '<snipped>'} {'params': {'state': 'opened', 'order_by': 'created_at', 'sort': 'asc', 'page': '2', 'per_page': '100'}}
2019-06-01 02:12:09,074 DEBUG Starting new HTTPS connection (1): gitlab.com
```

Logging stops at this point, and never recovers.  We seem to see this issue once every week, at random.
