### ISSUE TITLE
Maximum number of reassigns 

### ISSUE THREAD

**Issue by sobolevn** [smarkets/marge-bot#189]
When `marge` user creates a merge request and is assigned to merge it, infinite loop happens.

<img width="923" alt="Снимок экрана 2019-05-14 в 16 00 05" src="https://user-images.githubusercontent.com/4660275/57699856-66cb1000-7661-11e9-8e64-96ec902cecb3.png">
<img width="1188" alt="Снимок экрана 2019-05-14 в 15 59 46" src="https://user-images.githubusercontent.com/4660275/57699857-66cb1000-7661-11e9-94f9-b137eb9b50d6.png">

And there's no stopping mechanism. I suggest to add something like `--max-reassigns` option to stop it.

Or to check if future assignee and author is the same user. It might be easier.

**Comment by aschmolck** [comment]
I think your suggestion of marge-bot not unassigning itself just to re-assigning to itself is the right one, I'd be happy to accept a PR to that effect.

This is just a minor issue, because it shouldn't happen outside people testing their marge-bot setup, but I agree it would nonetheless good to fix.

**Comment by micheelengronne** [comment]
Related https://github.com/smarkets/marge-bot/issues/202

**Comment by micheelengronne** [comment]
MR https://github.com/smarkets/marge-bot/pull/203
