### ISSUE TITLE
branch-regexp but for source branch

### ISSUE THREAD

**Issue by micheelengronne** [smarkets/marge-bot#205]
Is it possible to add an option, source-branch-regexp that works like branch-regexp but for source branches ?

**Comment by aschmolck** [comment]
I'm happy to accept a MR that does this, since I think it might have other uses than running all bots under a single account (which is still not something I feel to be very desirable). Marge-bot should probably leave a single comment on the MR that it will be ignored because it doesn't match source-branch-regexp to prevent potential confusion.

**Comment by micheelengronne** [comment]
MR https://github.com/smarkets/marge-bot/pull/206
