### ISSUE TITLE
Automatic monitoring MRs without explicit assignment

### ISSUE THREAD

**Issue by okainov** [smarkets/marge-bot#220]
(disclaimer: I haven't tried it yet, just was reading docs and description)

Would it be possible to configure marge to do not wait for assignment of MRs to her, but just constantly monitor available MRs and do rebase automatically?

So I would like to use marge not as merge-bot, but as rebase-bot - just to rebase MRs when available.

**Comment by aschmolck** [comment]
I think this is out of scope, because it would need to behave quite differently from marge's normal operation to be useful. Right now marge operates a queue of MRs, ordered by submission time, and the only way a MR advances in the queue is if marge unassigns itself (or gets unassigned by a human) from MRs higher in the queue, either because of a successful merge or because e.g. CI failed an marge is unable to proceed further. For some automated rebase bot you'd probably want to rebase everything at periodic intervals, but that's expensive even if you just do it after a marge-controlled merge to master because you now need to run CI on all open MRs again all at once (as opposed to just the next one in the queue). Basically you go from O(M) to O(M^2).

Do you have some killer use case for this?

**Comment by okainov** [comment]
> For some automated rebase bot you'd probably want to rebase everything at periodic intervals, but that's expensive even if you just do it after a marge-controlled merge to master because you now need to run CI on all open MRs again all at once (as opposed to just the next one in the queue). Basically you go from O(M) to O(M^2).

If you take naive approach (go thru all, if can rebase - click rebase, continue; if can merge - merge, continue) then of course it's not really optimal. But you can compose your queue out of MRs which can be considered "good enough". And the thing is that "good enough" can be determined quite easily - have all approvals, have green "rebase" button or have green "merge" button (in terms of API, of course). If MR can be merged - then just take it to the queue and merge. There is no really need to have an explicit assignment.

**Comment by aschmolck** [comment]
Why would one want this (i.e. what concrete problem would the proposed behavior solve)? If everything looks good, the reviewer can upon approving just assign to marge (this is what we typically do, but it's useful to be be able to approve something without marge taking further action, because sometimes you want more control when things will actually be merged).

**Comment by okainov** [comment]
Eliminates extra human action.
"Review" - "Click approve" - "assign to marge" 
vs
"Review" - "Click approve" (merge&rebase done automatically if available)

If you got me wrong, I'm not suggesting to change default workflow, but add possibility to follow different workflow (i.e. with some option or config)

**Comment by snim2** [comment]
I'm pretty sure reviewer approvals are only available on paid GitLab tiers, so this would be a problematic default for anyone using the paid gitlab.org instance.

**Comment by aschmolck** [comment]
I don't think that feature would pull its weight.

**Comment by chaoflow** [comment]
@okainov You should be able to achieve this using [grge](https://gitlab.com/ApexAI/grge) in addition to marge and a rebase action for merge requests should be easy to implement.

Disclaimer: I'm one of the authors of grge.
