### ISSUE TITLE
Allow configuring the git ssh command

### ISSUE THREAD

**Issue by aclemons** [smarkets/marge-bot#235]
I need to configure the git ssh command to be `git-ssh-proxy` in an enviroment. Could we make GIT_SSH_COMMAND configurable for this?

**Comment by aclemons** [comment]
I've opened a PR with a possible solution.

**Comment by RobertKirk** [comment]
Why do you need the git ssh command to be a different command?

**Comment by aclemons** [comment]
In our environment, we need need to use a proxy. Something like:

`/usr/bin/ssh -o ProxyCommand='nc -X connect -x gateway:8080 %h %p' -o StrictHostKeyChecking=no`

**Comment by RobertKirk** [comment]
If you want to add the option (which I'm not against, as we don't allow configuring the ssh command currently), could you add it to all the other places that configuration options can be set? off the top of my head
* documentation (just the `README.md` I think)
* `marge/app.py` for passing in configuration on the command line
  * You'll then need to pass the configuration through to the `RepoManager` and then to `Repo` so that the option is overwridden in the `Repo.git` command.

It'd be good to write a test as well.

**Comment by matthiasbalke** [comment]
Maybe cloning using HTTPS (#283) is a valid alternative for you @aclemons

**Comment by aclemons** [comment]
Closing this, since I no longer need it and it seems no one else does either. Feel free to re-open if needed.
