### ISSUE TITLE
Missing support for gitlab-CE

### ISSUE THREAD

**Issue by backfx** [smarkets/marge-bot#30]
Looks like marge-bot is only compatible with gitlab-EE. It uses the approval feature that is not available in gitlab-CE. The endpoint `/api/v4/projects/{id}/merge_requests/{id}/approvals` is also not part of the Community Editions API.

```25.7.2017 10:23:142017-07-25 08:23:14,388 DEBUG Starting new HTTP connection (1): gitlab
25.7.2017 10:23:142017-07-25 08:23:14,400 DEBUG http://gitlab:80 "GET /api/v4/projects/1/merge_requests/1/approvals HTTP/1.1" 404 None
25.7.2017 10:23:142017-07-25 08:23:14,401 DEBUG RESPONSE CODE: 404
25.7.2017 10:23:142017-07-25 08:23:14,401 DEBUG RESPONSE BODY: {'error': '404 Not Found'}
25.7.2017 10:23:142017-07-25 08:23:14,402 ERROR Unexpected Exception
25.7.2017 10:23:14Traceback (most recent call last):
25.7.2017 10:23:14  File "/nix/store/02cbi06m7hk3qccalxrc71c2abiax6nz-python3.6-marge-0.1.2/lib/python3.6/site-packages/marge/job.py", line 56, in execute
25.7.2017 10:23:14    approvals = merge_request.fetch_approvals()
25.7.2017 10:23:14  File "/nix/store/02cbi06m7hk3qccalxrc71c2abiax6nz-python3.6-marge-0.1.2/lib/python3.6/site-packages/marge/merge_request.py", line 121, in fetch_approvals
25.7.2017 10:23:14    approvals.refetch_info()
25.7.2017 10:23:14  File "/nix/store/02cbi06m7hk3qccalxrc71c2abiax6nz-python3.6-marge-0.1.2/lib/python3.6/site-packages/marge/approvals.py", line 15, in refetch_info
25.7.2017 10:23:14    self._info = self._api.call(GET(approver_url))
25.7.2017 10:23:14  File "/nix/store/02cbi06m7hk3qccalxrc71c2abiax6nz-python3.6-marge-0.1.2/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
25.7.2017 10:23:14    raise error(response.status_code, err_message)
25.7.2017 10:23:14marge.gitlab.NotFound: (404, {'error': '404 Not Found'})
```

Supporting both versions with suitable workflows would be awesome!

**Comment by jcpetruzza** [comment]
Indeed, as far as I can see, there is a priori nothing that should prevent marge-bot from running on CE. We are using EE ourselves and didn't have the chance so far of running it against CE, so thanks for reporting this!

We are hitting the `/api/v4/projects/{id}/merge_requests/{id}/approvals` endpoint early on to find out if the merge request has pending approvals (so that we don't waste time rebasing a merge request that we cannot merge) and this is were you see the error. Here we should detect that we are on CE and instead of hitting the REST endpoint, produce a "no approvals needed" response directly. I should be able to push a fix for this tomorrow.

**Comment by aschmolck** [comment]
@jcpetruzza I think this is the way to go for now. We could also consider optionally overloading 👍 as approval for CE. I did even think about this before in the context of enterprise edition, because gitlab EE lacks some negative approval feature, as found e.g. in Phabricator (i.e. a reviewer can block even if the minimum number of approver is already met; that's potentially handy if someone spotted a problem that others have missed). So you could use 👎 for that.

**Comment by jcpetruzza** [comment]
@backfx I've pushed a fix for this on the PR above; is it possible for you to run marge-bot from that branch and see if you find other issues on CE? (I don't currently have a CE instance at hand to try it myself).

**Comment by backfx** [comment]
@jcpetruzza Yes I can test your changes on a ubuntu container inside my docker environment. Can u shortly explain the steps I have to do for building marge-bot?

**Comment by jcpetruzza** [comment]
Sure. The easiest thing would be to install nix inside your ubuntu container and use that to build a docker image. That way we ensure you don't run into troubles with the wrong version of python (we may be using 3.6 syntax somewhere and ubuntu), git, etc. You can later uninstall if you want it by removing the `/nix` directory.

```bash
$ curl https://nixos.org/nix/install | sh   # will create a /nix directory, and add a line to your `~/.profile`
$ . ~/.profile  # so you get nix on your path, etc.

$ git clone git@github.com:smarkets/marge-bot.git
$ cd marge-bot
$ git checkout ce_compatibility

$ make dockerize  # this will produce a `marge-bot` docker image
$ docker run marge-bot --gitlab-url=...
```

If you run into any issues, just let me know!

**Comment by backfx** [comment]
I successfully build your branch on top of nixos/nix. With your fix it already merged some merge-requests on CE. I'll do some more tests later. But for now its very promising. Would say that you can close this issue.

Thank you very much!

**Comment by jcpetruzza** [comment]
Cool! I've merged the fix and made a new release, so the CE-compatible version is already available on docker-hub. Thanks for your help!
