### ISSUE TITLE
merge failure (405 method not allowed on merge)

### ISSUE THREAD

**Issue by glensc** [smarkets/marge-bot#42]
marge got:
```
Reporter   
I couldn't merge this branch: had some issue with gitlab, check my logs...
```

i checked the logs and it has:
```
marge-bot_1  | 2017-08-09 06:29:43,992 ERROR Unanticipated ApiError from Gitlab on merge attempt
marge-bot_1  | Traceback (most recent call last):
marge-bot_1  |   File "/nix/store/9vhc0sbcxii1s05sz755ws8gr46iynqw-python3.6-marge-0.2.0/lib/python3.6/site-packages/marge/job.py", line 136, in rebase_and_accept
marge-bot_1  |     merge_request.accept(remove_branch=True, sha=actual_sha)
marge-bot_1  |   File "/nix/store/9vhc0sbcxii1s05sz755ws8gr46iynqw-python3.6-marge-0.2.0/lib/python3.6/site-packages/marge/merge_request.py", line 104, in accept
marge-bot_1  |     sha=sha or self.sha,  # if provided, ensures what is merged is what we want (or fails)
marge-bot_1  |   File "/nix/store/9vhc0sbcxii1s05sz755ws8gr46iynqw-python3.6-marge-0.2.0/lib/python3.6/site-packages/marge/gitlab.py", line 55, in call
marge-bot_1  |     raise error(response.status_code, err_message)
marge-bot_1  | marge.gitlab.MethodNotAllowed: (405, {'message': '405 Method Not Allowed'})
marge-bot_1  | 2017-08-09 06:29:44,545 WARNING I couldn't merge this branch: had some issue with gitlab, check my logs...
```

questions:
1. what could be cause, is it temporary error?
2. how to make marge retry?

i changed marge user access from reporter to developer, i used reporter before because such privilege worked in earlier project (marge itself is admin), but i don't see how to make marge retry. i even force pushed last commit removing the tested-by lines and restarted the bot docker container.

**Comment by lauripiisang** [comment]
Maybe (y)our webserver doesn't support PUT method?

**Comment by glensc** [comment]
@lauripiisang it worked before in the same gitlab instance in another project.

**Comment by jcpetruzza** [comment]
Unfortunately, GitLab doesn't provide much info when it rejects a merge. So, you say this is something that happens on one project only; does it happen consistently on every merge request for this project or was it only this occurrence? If the former, I'd bet it is is either "Push Rules" for the project or a custom git-hook installed that are rejecting the merge, e.g. because marge-bot's user's email is not white-listed. When this was the case, GitLab would sometimes leave some message in `gitlab-rails/githost.log`, so it may be a good idea to check for that.

Incidentally, I've noticed that GitLab sets the merge-request status to `reopened` when this happens, so I'm planning to add a check for this on failure, so that the error you get points you in the right direction.

If it was only for this particular merge-request, do you notice anything particular about it? Is it marked as WIP? Does it have the "squash commits" option ticked?

In any case, if you re-assign it to marge, it will be retried.

**Comment by glensc** [comment]
i'm using gitlab-ce, so squash-commits option does not exist. i do not have any custom git push rules either. and i managed to retry (don't remember how exactly) and then it managed to merge ok.

there's nothing in githost.log either, only few repack messages.

closing as unable to provide more details, so i assume it was some kind of temporary error.
