### ISSUE TITLE
merge failure because base branch not updated

### ISSUE THREAD

**Issue by glensc** [smarkets/marge-bot#47]
```
marge-bot_1  | 2017-08-17 11:47:36,764 INFO Processing !39 - 'Add 360 video support, DVID-103'
marge-bot_1  | 2017-08-17 11:47:36,944 INFO Running git -C /tmpa7qybnrd/tmphn_oz1jn fetch origin
marge-bot_1  | 2017-08-17 11:47:37,667 INFO Running git -C /tmpa7qybnrd/tmphn_oz1jn checkout -B DVID-103_add_360_video_support origin/DVID-103_add_360_video_support --
marge-bot_1  | 2017-08-17 11:47:37,687 INFO Running git -C /tmpa7qybnrd/tmphn_oz1jn rebase origin/master
marge-bot_1  | 2017-08-17 11:47:37,777 WARNING git returned 128
marge-bot_1  | 2017-08-17 11:47:37,777 WARNING stdout: b'First, rewinding head to replay your work on top of it...\nApplying: change1\nApplying: change2\nApplying: change3\nUsing index info to reconstruct a base tree...\nM\tfile1.php\nM\tfile2.php\nFalling back to patching base and 3-way merge...\nAuto-merging file2.php\nCONFLICT (content): Merge conflict in file2.php\nAuto-merging file1.php\nCONFLICT (content): Merge conflict in file1.php\nPatch failed at 0003 change1\nThe copy of the patch that failed is found in: .git/rebase-apply/patch\n\nWhen you have resolved this problem, run "git rebase --continue".\nIf you prefer to skip this patch, run "git rebase --skip" instead.\nTo check out the original branch and stop rebasing, run "git rebase --abort".\n\n'
marge-bot_1  | 2017-08-17 11:47:37,777 WARNING stderr: b'error: Failed to merge in the changes.\n'
marge-bot_1  | 2017-08-17 11:47:37,778 WARNING rebase failed, doing an --abort
marge-bot_1  | 2017-08-17 11:47:37,778 INFO Running git -C /tmpa7qybnrd/tmphn_oz1jn rebase --abort
marge-bot_1  | 2017-08-17 11:47:37,823 INFO Running git -C /tmpa7qybnrd/tmphn_oz1jn checkout master --
marge-bot_1  | 2017-08-17 11:47:37,833 INFO Running git -C /tmpa7qybnrd/tmphn_oz1jn branch -D DVID-103_add_360_video_support
marge-bot_1  | 2017-08-17 11:47:37,837 WARNING I couldn't merge this branch: got conflicts while rebasing, your problem now...
```

when i check workspace of marge bot, it's at `4d81b82`, but real `origin/master` is at `8fba43a`
and therefore the merge conflicts because base branch is out of date.

also seems that `origin` master is fetched and up to date. perhaps merge against `origin/master` not `master`?

```
bash-4.4# GIT_DIR=/tmpa7qybnrd/tmphn_oz1jn/.git /nix/store/m9wmmxajfxpw06sn0wv3gmvda2zlgmv2-git-2.13.3/bin/git show -s HEAD
commit 4d81b823fb7038b90a36bd2a8bd9da378a0e111a (HEAD -> master)


bash-4.4# GIT_DIR=/tmpa7qybnrd/tmphn_oz1jn/.git /nix/store/m9wmmxajfxpw06sn0wv3gmvda2zlgmv2-git-2.13.3/bin/git show -s master
commit 4d81b823fb7038b90a36bd2a8bd9da378a0e111a (HEAD -> master)

bash-4.4# GIT_DIR=/tmpa7qybnrd/tmphn_oz1jn/.git /nix/store/m9wmmxajfxpw06sn0wv3gmvda2zlgmv2-git-2.13.3/bin/git show -s origin/master
commit 8fba43a37831666af74a6b5de71cd6089ccf71c9 (origin/master, origin/HEAD)
Merge: 4e24499 dcb781f
bash-4.4#
```

**Comment by glensc** [comment]
my docker image version:

```
# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
smarketshq/marge-bot                          latest              22433019da23        47 years ago        275.9 MB

```

**Comment by glensc** [comment]
also i think `git reset --hard master origin/master` is needed if someone does force push on master branch. but i still think it's just simplier to rebase against `origin/master` than local `master` branch

default git fetch configuration will overwrite changes in `origin/*`

**Comment by jcpetruzza** [comment]
I'm not sure I understand if there is indeed an issue here. It is true that in the end the, repo points to (local) `master` and not `origin/master` but as I understand it that shouldn't be a problem:

Assume we start with the repo in `master`, which as you observe, may be different from `origin/master`. We then do (following the pasted log above):
  1. `git fetch origin`, so we are still in `master`, but `origin/master` and `origin/merge-request-branch` are up-to date.
  1. `git checkout -B merge-request-branch origin/merge-request-branch --`, so now the working branch is the branch to be rebased
  1. `git rebase origin/master`, here we rebase against the remote master branch, and fail because of a merge conflict.

So up to this point, everything has been done as one would expect. The following steps are just clean-ups, aimed to leaving the repo i) in a usable state (`git rebase --abort`), and ii) with a minimum number of branches (`git checkout master; git branch -D merge-request-branch`).

So we end up in `master` only because it is a branch we can assume exists locally. Does this make sense?

**Comment by glensc** [comment]
ok, looking the log i pasted, indeed the rebase is done on `origin/master` after `fetch origin`. so it's behaving as i suggested. and i have no clues why the rebase failed in that scenario.

closing as i have no more information or suggestions to add.
